app/main/__init__.py
'''
Author: andy
Date: 2023-06-06 01:05:59
LastEditors: andy
LastEditTime: 2023-06-06 01:48:36
Description: app 主功能視圖藍圖
'''

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
'''
Author: andy
Date: 2023-06-06 01:48:42
LastEditors: andy
LastEditTime: 2023-06-08 04:58:08
Description: app 主試圖
'''

from datetime import datetime

from flask import render_template, request, redirect, url_for, flash, abort
from flask_login import login_required, current_user

from app import db
from app.db_model import Record, RecordType, Project
from . import main


@main.route("/")
def index():
    return render_template("main/index.html")


@main.route("/record", methods=["GET"])
@login_required
def records():
    """顯示所有記帳路由"""

    user = current_user

    records = user.records

    return render_template("main/records.html", records=records)


@main.route("/add_record", methods=["GET", "POST"])
@login_required
def add_record():
    """新增記帳路由"""

    user = current_user

    if request.method == "POST":
        name = request.form.get("name")
        price = request.form.get("price")
        desc = request.form.get("desc")
        date = request.form.get("date")
        type_id = request.form.get("select_type")
        project_id = request.form.get("select_project")
        select_in_out = request.form.get("select_in_out")

        date_object = datetime.strptime(date, "%Y-%m-%d").date()

        # 支出
        if int(select_in_out) == 0:
            if int(price) > 0:
                price = -int(price)

        # 收入
        else:
            if int(price) < 0:
                price = -int(price)

        record = Record(name=name, price=price, desc=desc, date=date_object)

        user.records.append(record)

        if int(project_id) != 0:
            project = Project.query.get_or_404(project_id)

            project.current_price = project.current_price + int(price)
            project.records.append(record)

        db.session.add(record)
        db.session.commit()

        record_type = RecordType.query.get_or_404(type_id)
        record_type.records.append(record)
        db.session.commit()

        flash("新增成功")
        return redirect(url_for("main.records"))

    r_types = user.record_types
    u_projects = user.projects

    return render_template("main/add_record.html", r_types=r_types, projects=u_projects)


@main.route("/edit_record/<id>", methods=["GET", "POST"])
@login_required
def edit_record(id):
    """編輯記帳紀錄路由"""

    user = current_user
    record = Record.query.get_or_404(id)

    if record.user != user:
        abort(403)

    if request.method == "POST":
        name = request.form.get("name")
        price = request.form.get("price")
        desc = request.form.get("desc")
        date = request.form.get("date")
        type_id = request.form.get("select_type")
        project_id = request.form.get("select_project")
        select_in_out = request.form.get("select_in_out")

        date_object = datetime.strptime(date, "%Y-%m-%d").date()

        type_obj = RecordType.query.get_or_404(type_id)

        # 支出
        if int(select_in_out) == 0:
            if int(price) > 0:
                price = -int(price)

        # 收入
        else:
            if int(price) < 0:
                price = -int(price)

        # 變更分類
        if type_obj != record.type:
            record.type_id = type_obj.id

        # 變更專案
        if int(project_id) != 0:
            project_obj = Project.query.get_or_404(project_id)

            # 如果變更專案
            if record.project != project_obj:
                old_project = record.project

                # 處理餘額
                project_obj.current_price += record.price

                if old_project:
                    old_project.current_price -= record.price

                # 處理關聯
                project_obj.records.append(record)

            # 依照原有的專案
            else:
                # 處理餘額
                project_obj.current_price -= record.price
                project_obj.current_price += int(price)

        else:
            old_project = record.project
            if old_project:
                old_project.current_price -= record.price
                old_project.records.remove(record)

        record.name = name
        record.price = price
        record.desc = desc
        record.date = date_object

        db.session.commit()

        flash("更新成功")

        return redirect(url_for("main.records"))

    r_types = user.record_types
    projects = user.projects

    is_in = bool(record.price > 0)

    if not is_in:
        pprice = -record.price

    else:
        pprice = record.price

    return render_template(
        "main/edit_record.html",
        record=record,
        r_types=r_types,
        projects=projects,
        is_in=is_in,
        pprice=pprice,
    )


@main.route("/delete_record/<id>")
@login_required
def delete_record(id):
    """刪除記帳紀錄路由"""

    user = current_user
    record = Record.query.get_or_404(id)

    if record.user != user:
        abort(403)

    if record.project:
        record.project.current_price -= record.price

    user.records.remove(record)

    db.session.commit()

    flash("刪除成功")

    return redirect(url_for("main.records"))


@main.route("/record_types")
@login_required
def record_types():
    """所有記帳種類路由"""

    user = current_user

    types = user.record_types

    return render_template("main/record_types.html", types=types)


@main.route("/record_type/<id>")
@login_required
def record_type(id):
    """單一記帳種類路由"""

    user = current_user

    r_type = RecordType.query.get_or_404(id)

    if r_type.user != user:
        abort(403)

    records = r_type.records

    return render_template("main/record_type.html", r_type=r_type, records=records)


@main.route("/add_record_type", methods=["GET", "POST"])
@login_required
def add_record_type():
    """新增記帳種類路由"""

    user = current_user

    if request.method == "POST":
        name = request.form.get("name")
        desc = request.form.get("desc")

        r_type = RecordType(name=name, desc=desc)

        user.record_types.append(r_type)

        db.session.add(r_type)
        db.session.commit()

        flash("新增成功")

        return redirect(url_for("main.record_types"))

    return render_template("main/add_record_type.html")


@main.route("/edit_record_type/<id>", methods=["GET", "POST"])
@login_required
def edit_record_type(id):
    """編輯記帳種類路由"""

    user = current_user
    r_type = RecordType.query.get_or_404(id)

    if r_type.user != user:
        abort(403)

    if request.method == "POST":
        name = request.form.get("name")
        desc = request.form.get("desc")

        r_type.name = name
        r_type.desc = desc

        db.session.commit()

        flash("更新成功")

        return redirect(url_for("main.record_types"))

    return render_template("main/edit_record_type.html", r_type=r_type)


@main.route("/delete_record_type/<id>")
@login_required
def delete_record_type(id):
    """刪除記帳種類"""

    user = current_user
    r_type = RecordType.query.get_or_404(id)

    if r_type.user != user:
        abort(403)

    if r_type.records:
        for record in r_type.records:
            record.project.current_price -= record.price

    user.record_types.remove(r_type)
    db.session.commit()

    flash("刪除成功")

    return redirect(url_for("main.record_types"))


@main.route("/projects")
@login_required
def projects():
    """所有專案路由"""

    user = current_user

    projects = user.projects

    return render_template("main/projects.html", projects=projects)


@main.route("/project/<id>")
@login_required
def project(id):
    """單一專案路由"""

    user = current_user
    u_project = Project.query.get_or_404(id)

    if u_project.user != user:
        abort(403)

    records = u_project.records

    return render_template("main/project.html", project=u_project, records=records)


@main.route("/add_project", methods=["GET", "POST"])
@login_required
def add_project():
    """新增專案路由"""

    user = current_user

    if request.method == "POST":
        name = request.form.get("name")
        price = request.form.get("price")
        desc = request.form.get("desc")
        date = request.form.get("date")

        date_object = datetime.strptime(date, "%Y-%m-%d").date()

        project = Project(name=name, price=price, current_price=price, desc=desc, date=date_object)

        user.projects.append(project)

        db.session.add(project)
        db.session.commit()

        flash("新增成功")
        return redirect(url_for("main.projects"))

    return render_template("main/add_project.html")


@main.route("/edit_project/<id>", methods=["GET", "POST"])
@login_required
def edit_project(id):
    """編輯專案路由"""

    user = current_user
    project = Project.query.get(id)

    if project.user != user:
        abort(403)

    if request.method == "POST":
        name = request.form.get("name")
        price = request.form.get("price")
        desc = request.form.get("desc")
        date = request.form.get("date")

        date_object = datetime.strptime(date, "%Y-%m-%d").date()

        tmp_price = project.price - project.current_price

        project.name = name
        project.price = price
        project.current_price = int(price) - tmp_price
        project.desc = desc
        project.date = date_object

        db.session.commit()

        flash("更新完成")

        return redirect(url_for("main.projects"))

    return render_template("main/edit_project.html", project=project)


@main.route("/delete_projcet/<id>")
@login_required
def delete_project(id):
    """刪除專案路由"""

    user = current_user
    project = Project.query.get(id)

    if project.user != user:
        abort(403)

    user.projects.remove(project)
    db.session.commit()

    flash("刪除成功")

    return redirect(url_for("main.projects"))

app/templates/main/add_record.html
{% extends 'base.html' %}

{% block title %} 新增紀錄 {% endblock %}

{% block page %}

{% if not r_types %}
<div class="alert alert-danger" role="alert">
    你還沒有任何的分類，請先新增一個分類 <a href="{{ url_for('main.add_record_type') }}" class="alert-link">新增分類</a>
</div>
{% endif %}

<div class="page-container">
    <div class="items-container">
        <div class="login-container">
            <div class="login-header">
                <h4>
                    <img src="{{ url_for('static', filename = 'images/add.png') }}"
                        class="d-inline-block align-text-top">
                    新增一筆記帳
                </h4>
            </div>
            <div class="form-container">
                <form class="row g-3" action="{{ url_for('main.add_record') }}" method="POST">
                    <div class="mb-3">
                        <label for="type" class="form-label">分類</label>
                        {% if r_types %}
                        <select class="form-select" aria-label="Default select example" name="select_type">
                            {% for r_type in r_types %}
                            <option value="{{ r_type.id }}">{{ r_type.name }}</option>
                            {% endfor %}
                        </select>
                        {% else %}
                        <h4>還沒有任何分類</h4>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="select_project" class="form-label">專案</label>
                        <select class="form-select" aria-label="Default select example" name="select_project">
                            <option value="0" selected>無</option>
                            {% for project in projects %}
                            <option value="{{ project.id }}">{{ project.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="select_in_out" class="form-label">收入或支出</label>
                        <select class="form-select" aria-label="Default select example" name="select_in_out">
                            <option value="0" selected>支出</option>
                            <option value="1">收入</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="name" class="form-label">名稱</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="早餐" required>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="form-label">價格</label>
                        <input type="number" class="form-control" id="price" name="price" placeholder="110" required>
                    </div>
                    <div class="mb-3">
                        <label for="desc" class="form-label">備註</label>
                        <input type="text" class="form-control" id="desc" name="desc" placeholder="茶葉蛋、豆漿">
                    </div>
                    <div class="mb-3">
                        <label for="date" class="form-label">日期</label>
                        <input type="date" class="form-control" id="date" name="date">
                    </div>
                    <div class="col-12">
                        {% if r_types %}
                        <button type="submit" class="btn btn-outline-primary">
                            <img src="{{ url_for('static', filename = 'images/add.png') }}" width="24" height="24"
                                class="d-inline-block align-text-top">
                            新增
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-outline-primary" disabled>
                            <img src="{{ url_for('static', filename = 'images/add.png') }}" width="24" height="24"
                                class="d-inline-block align-text-top">
                            新增
                        </button>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>

    // NOTE 使用 ChatGPT
    // 取得目前日期
    var currentDate = new Date();

    // 轉成 UTC8
    var utcOffset = 8;
    var utcOffsetMilliseconds = utcOffset * 60 * 60 * 1000;
    var utcPlus8Date = new Date(currentDate.getTime() + utcOffsetMilliseconds);

    // 轉換格式成 YYYY-MM-DD
    var formattedDate = utcPlus8Date.toISOString().split('T')[0];

    // 設定默認日期
    document.getElementById('date').value = formattedDate;
</script>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}

{% block page %}
<div class="page-container">
    <div class="page-header">
        <p class="text-center fs-2">歡迎使用 P記帳</p>
    </div>

    <div class="items-container index">
        {% if current_user.is_authenticated %}
        <div class="col-12">
            <a href="{{ url_for('main.add_record') }}" class="btn btn-outline-primary" role="button">
                <img src="{{ url_for('static', filename = 'images/collection.png') }}" width="24" height="24"
                    class="d-inline-block align-text-top">
                新增一筆記帳
            </a>
            <a href="{{ url_for('main.add_project') }}" class="btn btn-outline-primary" role="button">
                <img src="{{ url_for('static', filename = 'images/project.png') }}" width="24" height="24"
                    class="d-inline-block align-text-top">
                新增一個專案
            </a>
        </div>
        {% else %}
        <div class="col-12">
            <a href="{{ url_for('auth.login') }}" class="btn btn-outline-primary" role="button">
                <img src="{{ url_for('static', filename = 'images/login.png') }}" width="24" height="24"
                    class="d-inline-block align-text-top">
                請先登入
            </a>
            <a href="{{ url_for('auth.register') }}" class="btn btn-outline-success" role="button">
                <img src="{{ url_for('static', filename = 'images/register.png') }}" width="24" height="24"
                    class="d-inline-block align-text-top">
                或是註冊
            </a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/main/project.html
{% extends 'base.html' %}

{% block title %} 專案 {{ project.name }} {% endblock %}


{% block page %}
<div class="page-container">
    <div class="page-header">
        <h2>專案: {{ project.name }}</h2>
    </div>

    <div class="items-container">
        <h3>記帳紀錄</h3>
        {% if not records %}
        <h4>還沒有任何紀錄</h4>
        <div class="mb-3">
            <a href="{{ url_for('main.add_record') }}" class="btn btn-outline-primary" role="button">
                <img src="{{ url_for('static', filename = 'images/add.png') }}" width="24" height="24"
                    class="d-inline-block align-text-top">
                新增一筆記帳
            </a>
        </div>
        {% endif %}
        <ul class="list-group">
            {% for r in records %}
            <li class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">名稱: {{ r.name }} </h5>
                    <small>{{ r.date }}</small>
                </div>
                <p class="mb-1">$ {{ r.price}}</p>
                <p class="mb-1">分類: <a href="{{ url_for('main.record_type', id=r.type.id) }}">{{ r.type.name }}</a></p>
                <small>
                    備註:
                    {% if r.desc %}
                    {{ r.desc }}
                    {% else %}
                    無
                    {% endif %}
                </small>
                <div class="d-flex justify-content-start">
                    <a href="{{ url_for('main.edit_record', id=r.id) }}" class="btn btn-outline-primary"
                        role="button">編輯</a>
                    <a href="{{ url_for('main.delete_record', id=r.id) }}" class="btn btn-outline-danger"
                        role="button">刪除</a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

app/templates/main/projects.html
{% extends 'base.html' %}

{% block title %} 專案一覽 {% endblock %}


{% block page %}
<div class="page-container">
    <div class="page-header">
        <h2>
            <img src="{{ url_for('static', filename = 'images/project.png') }}" class="d-inline-block align-text-top">
            專案一覽
        </h2>
    </div>

    <div class="items-container">
        <div class="mb-3">
            <a href="{{ url_for('main.add_project') }}" class="btn btn-outline-primary" role="button">
                <img src="{{ url_for('static', filename = 'images/add.png') }}" width="24" height="24"
                    class="d-inline-block align-text-top">
                新增一個專案
            </a>
        </div>

        {% if not projects %}
        <h4>還沒有任何專案</h4>
        {% endif %}
        <ul class="list-group">
            {% for p in projects %}
            <li class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><a href="{{ url_for('main.project', id = p.id) }}">名稱: {{ p.name }}</a> </h5>
                </div>
                <p class="mb-1">預算 $ {{ p.price}}</p>
                <p class="mb-1">目前餘額 $ {{ p.current_price}}</p>
                <small>
                    備註:
                    {% if p.desc %}
                    {{ p.desc }}
                    {% else %}
                    無
                    {% endif %}
                </small>
                <div class="d-flex justify-content-start">
                    <a href="{{ url_for('main.edit_project', id = p.id) }}" class="btn btn-outline-success"
                        role="button">
                        <img src="{{ url_for('static', filename = 'images/edit.png') }}" width="24" height="24"
                            class="d-inline-block align-text-top">
                        編輯
                    </a>
                    <a href="#" class="btn btn-outline-danger" role="button" data-bs-toggle="modal"
                        data-bs-target="#projectDeleteModal">
                        <img src="{{ url_for('static', filename = 'images/delete.png') }}" width="24" height="24"
                            class="d-inline-block align-text-top">
                        刪除
                    </a>
                </div>

                <div class="modal fade" id="projectDeleteModal" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">確定要刪除專案: {{ p.name }} 嗎？</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                刪除後就無法復原喔！
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <a href="{{ url_for('main.delete_project', id=p.id)}}" class="btn btn-outline-danger"
                                    role="button">確定刪除</a>

                            </div>
                        </div>
                    </div>
                </div>

            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

app/templates/main/record.html
{% extends 'base.html' %}

{% block title %} 記帳紀錄 {% endblock %}


{% block page %}
<div class="page-container">
    <div class="page-header">
        <h2>記帳紀錄</h2>
    </div>

    <div class="items-container">
        <div class="list-group">
            {% for r in record %}
            <a href="#" class="list-group-item list-group-item-action" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">名稱: {{ r.name }} </h5>
                    <small>{{ r.date }}</small>
                </div>
                <p class="mb-1">$ {{ r.price}}</p>
                <small>備註: {{ r.desc }}</small>
            </a>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/main/record_type.html
{% extends 'base.html' %}

{% block title %} 記帳分類 - {{ r_type.name }} {% endblock %}


{% block page %}
<div class="page-container">
    <div class="page-header">
        <h2>分類: {{ r_type.name }}</h2>
    </div>

    <div class="items-container">
        <h3>記帳紀錄</h3>
        {% if not records %}
        <h4>還沒有任何紀錄</h4>
        <div class="mb-3">
            <a href="{{ url_for('main.add_record') }}" class="btn btn-outline-primary" role="button">
                <img src="{{ url_for('static', filename = 'images/add.png') }}" width="24" height="24"
                    class="d-inline-block align-text-top">
                新增一筆記帳
            </a>
        </div>
        {% endif %}
        <ul class="list-group">
            {% for r in records %}
            <li class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">名稱: {{ r.name }} </h5>
                    <small>{{ r.date }}</small>
                </div>
                <p class="mb-1">$ {{ r.price}}</p>
                <small>
                    備註:
                    {% if r.desc %}
                    {{ r.desc }}
                    {% else %}
                    無
                    {% endif %}
                </small>
                <div class="d-flex justify-content-start">
                    <a href="{{ url_for('main.edit_record', id=r.id) }}" class="btn btn-outline-primary"
                        role="button">編輯</a>
                    <a href="{{ url_for('main.delete_record', id=r.id) }}" class="btn btn-outline-danger"
                        role="button">刪除</a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

app/templates/main/record_types.html
{% extends 'base.html' %}

{% block title %} 分類一覽 {% endblock %}


{% block page %}
<div class="page-container">
    <div class="page-header">
        <h2>
            <img src="{{ url_for('static', filename = 'images/collection.png') }}"
                class="d-inline-block align-text-top">
            記帳分類
        </h2>
    </div>

    <div class="items-container">
        <div class="mb-3">
            <a href="{{ url_for('main.add_record_type') }}" class="btn btn-outline-primary" role="button">
                <img src="{{ url_for('static', filename = 'images/add.png') }}" width="24" height="24"
                    class="d-inline-block align-text-top">
                新增一個分類
            </a>
        </div>

        {% if not types %}
        <h4>還沒有任何分類</h4>
        {% endif %}
        <ul class="list-group">
            {% for t in types %}
            <li class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><a href="{{ url_for('main.record_type', id=t.id) }}">名稱: {{ t.name }}</a> </h5>
                </div>
                <small>
                    備註:
                    {% if t.desc %}
                    {{ t.desc }}
                    {% else %}
                    無
                    {% endif %}
                </small>
                <div class="d-flex justify-content-start">
                    <a href="{{ url_for('main.edit_record_type', id = t.id )}}" class="btn btn-outline-success"
                        role="button">
                        <img src="{{ url_for('static', filename = 'images/edit.png') }}" width="24" height="24"
                            class="d-inline-block align-text-top">
                        編輯
                    </a>
                    <a href="#" class="btn btn-outline-danger" role="button" data-bs-toggle="modal"
                        data-bs-target="#typeDeleteModal">
                        <img src="{{ url_for('static', filename = 'images/delete.png') }}" width="24" height="24"
                            class="d-inline-block align-text-top">
                        刪除
                    </a>
                </div>

                <div class="modal fade" id="typeDeleteModal" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">確定要刪除分類: {{ t.name }} 嗎？</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                注意 ** 會連帶把屬於這個分類的記帳紀錄也一起刪除 ** ，
                                刪除後就無法復原喔！
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <a href="{{ url_for('main.delete_record_type', id = t.id) }}"
                                    class="btn btn-outline-danger" role="button">確定刪除</a>
                            </div>
                        </div>
                    </div>
                </div>

            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

app/templates/main/records.html
{% extends 'base.html' %}

{% block title %} 記帳紀錄 {% endblock %}


{% block page %}
<div class="page-container">
    <div class="page-header">

        <h2>
            <img src="{{ url_for('static', filename = 'images/record.png') }}" class="d-inline-block align-text-top">
            記帳紀錄
        </h2>
    </div>

    <div class="items-container">
        <div class="mb-3">
            <a href="{{ url_for('main.add_record') }}" class="btn btn-outline-primary" role="button">
                <img src="{{ url_for('static', filename = 'images/add.png') }}" width="24" height="24"
                    class="d-inline-block align-text-top">
                新增一筆記帳
            </a>
        </div>

        {% if not records %}
        <h4>還沒有任何紀錄</h4>
        {% endif %}
        <ul class="list-group">
            {% for r in records %}
            <li class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">名稱: {{ r.name }} </h5>
                    <small>{{ r.date }}</small>
                </div>
                <p class="mb-1">$ {{ r.price}}</p>
                <p class="mb-1">分類: <a href="{{ url_for('main.record_type', id=r.type.id) }}">{{ r.type.name }}</a></p>
                <p class="mb-1">專案:
                    {% if r.project %}
                    <a href="{{ url_for('main.project', id=r.project.id)}}">{{ r.project.name }}</a>
                    {% else %}
                    無
                    {% endif %}
                </p>
                <small>
                    備註:
                    {% if r.desc %}
                    {{ r.desc }}
                    {% else %}
                    無
                    {% endif %}
                </small>
                <div class="d-flex justify-content-start">
                    <a href="{{ url_for('main.edit_record', id=r.id) }}" class="btn btn-outline-success" role="button">
                        <img src="{{ url_for('static', filename = 'images/edit.png') }}" width="24" height="24"
                            class="d-inline-block align-text-top">
                        編輯
                    </a>
                    <a href="#" class="btn btn-outline-danger" role="button" data-bs-toggle="modal"
                        data-bs-target="#recordDeleteModal">
                        <img src="{{ url_for('static', filename = 'images/delete.png') }}" width="24" height="24"
                            class="d-inline-block align-text-top">
                        刪除
                    </a>
                </div>

                <div class="modal fade" id="recordDeleteModal" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">確定要刪除紀錄: {{ r.name }} 嗎？</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                刪除後就無法復原喔！
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <a href="{{ url_for('main.delete_record', id=r.id) }}" class="btn btn-outline-danger"
                                    role="button">確定刪除</a>

                            </div>
                        </div>
                    </div>
                </div>

            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}